sudo: required
language: python

python:
    - 2.7
    - 3.4
    - 3.6

services:
    - docker

cache:
    directories:
     - /home/travis/.sbt/

env:
  global:
    - ASYNC_TEST_TIMEOUT=30
    - PATH=$PATH:/snap/bin

before_install:
    - mkdir -p $HOME/.sbt/launchers/1.2.1
    - curl -L -o $HOME/.sbt/launchers/1.2.1/sbt-launch.jar http://central.maven.org/maven2/org/scala-sbt/sbt-launch/1.2.1/sbt-launch-1.2.1.jar
    - sudo apt update

install:
    - pip install --upgrade setuptools pip websocket-client
    - make dist enterprise-gateway-demo
    - pip install dist/*.whl coverage
    - pip freeze
    - sudo apt install --yes snapd
    - sudo snap install microk8s --classic
    - sudo microk8s.start
    - microk8s.kubectl get all --all-namespaces

script:
    - jupyter enterprisegateway --help

after_success:
  - echo "Travis exited with ${TRAVIS_TEST_RESULT}"
  - python --version
  - pip --version
  - pip list
  - pip install codecov
  - codecov

after_failure:
  - echo "Travis exited with ${TRAVIS_TEST_RESULT}"
  - python --version
  - pip --version
  - pip list
  - docker logs itest-yarn
