sudo: required
language: python

python:
    - 2.7
    - 3.4
    - 3.6

services:
    - docker

cache:
    directories:
     - /home/travis/.sbt/

env:
  global:
    - ASYNC_TEST_TIMEOUT=30

before_install:
    - mkdir -p $HOME/.sbt/launchers/1.2.1
    - curl -L -o $HOME/.sbt/launchers/1.2.1/sbt-launch.jar http://central.maven.org/maven2/org/scala-sbt/sbt-launch/1.2.1/sbt-launch-1.2.1.jar

install:
    - pip install --upgrade setuptools pip websocket-client
    - make dist
    - pip install dist/*.whl coverage
    - pip freeze
    - echo "Starting local kubernetes cluster (minikube)"
    - curl -s -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.9.4/bin/linux/amd64/kubectl
    - chmod +x kubectl && sudo mv kubectl /usr/local/bin/
    - curl -s -Lo minikube https://storage.googleapis.com/minikube/releases/v0.25.1/minikube-linux-amd64
    - chmod +x minikube && sudo mv minikube /usr/local/bin/
    - sudo minikube start --vm-driver=none
    - sleep 15
    - sudo kubectl cluster-info

script:
    - sudo kubectl apply -f etc/kubernetes/enterprise-gateway.yaml && sleep 15
    - sudo kubectl get all -l app=enterprise-gateway --all-namespaces
    - nosetests -v enterprise_gateway.itests.test_python_kernel.TestPythonKernelKubernetes

after_success:
  - echo "Travis exited with ${TRAVIS_TEST_RESULT}"
  - python --version
  - pip --version
  - pip list
  - pip install codecov
  - codecov

after_failure:
  - echo "Travis exited with ${TRAVIS_TEST_RESULT}"
  - python --version
  - pip --version
  - pip list
  - docker logs itest-yarn
